# Generated by Django 5.0.7 on 2024-07-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_inventoryentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryentry',
            unique_together=set(),
        ),
    ]
